### ISSUE TITLE
FBAvatarRoot.tscn missing

### ISSUE THREAD

**Issue by guysoft** [mgschwan/VRWorkout#15]
Hey,
New to Godot development.
I am trying to run VRWorkout on my linux VR setup using HTC vive.
Hopfully manage to port this to linux :)

When I open the project I get that there is a dependency missing. FBAvatarRoot.tscn which I can see here.

This is the dialog I am getting:
![Screenshot_20210728_004734](https://user-images.githubusercontent.com/325670/127231945-a01d7813-e2e5-4a39-809c-8372a6d5fda8.png)

How should I fix this?

Will note I did get the basic VR tutorial to work.

Thanks!

**Comment by mgschwan** [comment]
Fixed in commit 93ef149a50a79f6d1cb40b219025d51815ab5b12
