### ISSUE TITLE
Launching gives the error: Could not create directory: /sdcard

### ISSUE THREAD

**Issue by guysoft** [mgschwan/VRWorkout#16]
```
E 0:00:00.005   make_dir_recursive: Could not create directory: /sdcard
  <C++ Error>   Method failed. Returning: err
  <C++ Source>  core/os/dir_access.cpp:184 @ make_dir_recursive()
```
Workaround was to create a ``/sdcard`` folder and give it 777 permissions. It wrote to the the vr_workout.txt log file.

Running from linux.

**Comment by mgschwan** [comment]
The game tries to determine if it's running on the Quest or Windows and selects the music directory accordingly. This does not seem to work for linux.
A workaround is to set the Music Directory in the project settings to something that is writeable by the user
