### ISSUE TITLE
Hand_palm.obj is missing on load, hand_palm.mtl does exist

### ISSUE THREAD

**Issue by guysoft** [mgschwan/VRWorkout#17]
Hey,
Still working on importing the project (been trying both linux and windows).

I got an error that hand_palm.obj is missing. There is a .blend file that I assume can be used to generate it. 
Though it seems like the mtl obj file does exist in the folder:
https://github.com/mgschwan/VRWorkout/blob/master/godot_project/models/hand_palm.mtl

But there is no
https://github.com/mgschwan/VRWorkout/blob/master/godot_project/models/hand_palm.obj

The error in godot is:
![cue_load_godot](https://user-images.githubusercontent.com/325670/127478311-6d5c42fb-7c1f-41f0-b830-64f7a3c760f6.png)

**Comment by mgschwan** [comment]
Did you update to the latest version today?
I added the missung obj and mtl file with the other changes yesterday

**Comment by mgschwan** [comment]
Sorry that was my bad, there was a stray .gitignore file in there that excluded obj files.
Should work now.

**Comment by guysoft** [comment]
Yea, I had to do ``--force`` to get the PR to work too :)

Ill test when I am next to a machine, though I am pretty sure when the obj file is there it loads.
On windows I didn't manage to get OpenVR to load. Will try on Linux perhaps later today or more likely tomorrow.
